CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    nombre_usuario VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    rol ENUM('ESTUDIANTE', 'INSTRUCTOR', 'ADMIN') DEFAULT 'ESTUDIANTE',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);